version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}

      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm

  snyk_scan:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}

      - run:
          name: Snyk Setup
          command: |
            curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
            chmod +x ./snyk
            sudo mv ./snyk /usr/local/bin/snyk
      - run:
          name: Snyk Test 
          command: |
            snyk auth $SNYK_TOKEN
            snyk monitor 
            snyk test --severity-threshold=critical --fail-on=patchable
workflows:
  example-workflow:
    jobs:
      - build
      - snyk_scan:
          requires:
            - build

